---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - autoscaling.bogo.ac.cn.cronvpa.bogo.ac.cn
  resources:
  - cronvpas
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - autoscaling.bogo.ac.cn.cronvpa.bogo.ac.cn
  resources:
  - cronvpas/finalizers
  verbs:
  - update
- apiGroups:
  - autoscaling.bogo.ac.cn.cronvpa.bogo.ac.cn
  resources:
  - cronvpas/status
  verbs:
  - get
  - patch
  - update
